# Generated by Django 5.1.5 on 2025-02-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('date_join', models.DateField()),
                ('date_leave', models.DateField()),
            ],
        ),
    ]
