# Generated by Django 5.1.5 on 2025-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_amo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoMipangokazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpangokazi', models.CharField(max_length=255)),
                ('tarehe_ya_kupanga', models.DateField()),
                ('wahusika', models.CharField(max_length=255)),
                ('gharama', models.DecimalField(decimal_places=2, max_digits=10)),
                ('namna', models.TextField()),
            ],
        ),
    ]
