# Generated by Django 5.1.5 on 2025-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_amomipangokazi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoTaarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpangokazi_done', models.CharField(max_length=255, verbose_name='Mpangokazi')),
                ('ufanisi', models.CharField(choices=[('ulitekelezwa', 'Utekelezwa'), ('haukutekelezwa', 'Haukutekelezwa')], default='ulitekelezwa', max_length=50, verbose_name='Ufanisi')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('sababu', models.TextField(verbose_name='Sababu za Kufanikiwa au La')),
                ('ushauri', models.TextField(verbose_name='Ushauri/Mapendekezo')),
            ],
        ),
    ]
