# Generated by Django 5.1.5 on 2025-02-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_amotaarifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCashReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBankTransaction', models.DateField()),
                ('dateOfCashTransaction', models.DateField()),
                ('bankDeposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cashDeposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bankWithdrawal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cashWithdrawals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CashBudgetRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('incomesource', models.CharField(max_length=255)),
                ('incomeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenseCategory', models.CharField(max_length=255)),
                ('expenseAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MipangokaziHazina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('aim', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experts', models.CharField(max_length=255)),
                ('method', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptsPerIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateindividual', models.DateField()),
                ('username', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direction', models.CharField(max_length=255)),
                ('confirmationStatus', models.CharField(max_length=50)),
                ('leaderName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('church', models.CharField(max_length=100)),
                ('baptism_status', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=100)),
                ('terms_agreement', models.BooleanField(default=False)),
            ],
        ),
    ]
