# Generated by Django 5.1.5 on 2025-02-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankcashreconciliation_cashbudgetrecords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipangokazihazina',
            name='cost',
            field=models.CharField(max_length=255),
        ),
    ]
