# Generated by Django 5.1.5 on 2025-02-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_mipangokazihazina_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipangokazihazina',
            name='date',
            field=models.CharField(max_length=7),
        ),
    ]
