# Generated by Django 5.1.5 on 2025-02-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_mipangokazihazina_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbudgetrecords',
            name='period',
            field=models.CharField(max_length=7),
        ),
    ]
