# Generated by Django 5.1.5 on 2025-02-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_cashbudgetrecords_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tithes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('matoleo_type', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direction', models.CharField(max_length=100)),
            ],
        ),
    ]
