# Generated by Django 5.1.5 on 2025-02-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_tithes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithes',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
