# Generated by Django 5.1.5 on 2025-02-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_tithes_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=255)),
                ('date_join', models.DateField()),
                ('date_leave', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('cv_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='accounts.elderinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpangokazi_done', models.CharField(max_length=255)),
                ('ufanisi', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sababu', models.TextField()),
                ('ushauri', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.elderinfo')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpangokazi', models.CharField(max_length=255)),
                ('tarehe_ya_kupanga', models.DateField()),
                ('wahusika', models.CharField(max_length=255)),
                ('gharama', models.DecimalField(decimal_places=2, max_digits=10)),
                ('namna', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plans', to='accounts.elderinfo')),
            ],
        ),
    ]
