# Generated by Django 5.1.5 on 2025-02-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_elderinfo_cv_feedback_workplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
                ('abled', models.IntegerField()),
                ('disabled', models.IntegerField()),
            ],
        ),
    ]
