# Generated by Django 5.1.5 on 2025-02-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
    ]
